# Multi-stage build for secure node production environment
FROM node:22-alpine AS builder
WORKDIR /app
COPY backend/package*.json ./
RUN npm ci
COPY backend/ .

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/db.js ./db.js
COPY --from=builder /app/server.js ./server.js

EXPOSE 4000
CMD ["node", "server.js"]
